server:
  port: 8803

spring:
  application:
    name: ribbon-client


#设置注册中心地址
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8888/eureka


