server:
  port: 8806



spring:
  application:
    name: hystrix-consumer
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8888/eureka
