spring:
  application:
    name: zuul-gateway

server:
  port: 8809


#设置注册中心地址
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8888/eureka

zuul:
  routes:
    api-a.path: /api-a/**
    api-a.serviceId: hello-service
    api-b.path: /api-b/**
    api-b.serviceId: feign-consumer

