server:
  port: 8805


spring:
  application:
    name: feign-consumer
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8888/eureka
